apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      run: mongo
  replicas: 1
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
      imagePullSecrets:
        - name: key
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pv-claim